language: android
jdk: oraclejdk8
sudo: false
git:
  depth: 1
android:
    components:
        - tools
        - platform-tools
        - tools
        - build-tools-28.0.3
        - android-28
        - extra-android-support
        - extra-android-m2repository

before_install:
  - yes | sdkmanager "platforms;android-28"

script:
  ./gradlew clean build
